[package]
name = "ollama"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "*"
serde_json = "*"
reqwest = { version = "*", features = ['json'] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "*"
futures = "*"
